### ISSUE TITLE
Fix linters-warning

### ISSUE THREAD

**Issue by brlin-tw** [brlin-tw/scrcpy-snap#1]
Refer to the following Snapcraft warning messages for the problem:

```yaml
Lint warnings:
- library: libGLX_mesa.so.0: unused library 'usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0'. (https://snapcraft.io/docs/linters-library)
- library: libcaca++.so.0: unused library 'usr/lib/x86_64-linux-gnu/libcaca++.so.0.99.19'. (https://snapcraft.io/docs/linters-library)
- library: libflite_cmu_grapheme_lang.so.1: unused library 'usr/lib/x86_64-linux-gnu/libflite_cmu_grapheme_lang.so.2.2'. (https://snapcraft.io/docs/linters-library)
- library: libflite_cmu_grapheme_lex.so.1: unused library 'usr/lib/x86_64-linux-gnu/libflite_cmu_grapheme_lex.so.2.2'. (https://snapcraft.io/docs/linters-library)
- library: libflite_cmu_indic_lex.so.1: unused library 'usr/lib/x86_64-linux-gnu/libflite_cmu_indic_lex.so.2.2'. (https://snapcraft.io/docs/linters-library)
- library: libflite_cmu_time_awb.so.1: unused library 'usr/lib/x86_64-linux-gnu/libflite_cmu_time_awb.so.2.2'. (https://snapcraft.io/docs/linters-library)
- library: libicuio.so.70: unused library 'usr/lib/x86_64-linux-gnu/libicuio.so.70.1'. (https://snapcraft.io/docs/linters-library)
- library: libicutest.so.70: unused library 'usr/lib/x86_64-linux-gnu/libicutest.so.70.1'. (https://snapcraft.io/docs/linters-library)
- library: libjacknet.so.0: unused library 'usr/lib/x86_64-linux-gnu/libjacknet.so.0.1.0'. (https://snapcraft.io/docs/linters-library)
- library: libjackserver.so.0: unused library 'usr/lib/x86_64-linux-gnu/libjackserver.so.0.1.0'. (https://snapcraft.io/docs/linters-library)
- library: libmfx-tracer.so.1: unused library 'usr/lib/x86_64-linux-gnu/libmfx-tracer.so.1.35'. (https://snapcraft.io/docs/linters-library)
- library: libmfxhw64.so.1: unused library 'usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.35'. (https://snapcraft.io/docs/linters-library)
- library: libsphinxad.so.3: unused library 'usr/lib/x86_64-linux-gnu/libsphinxad.so.3.0.0'. (https://snapcraft.io/docs/linters-library)
- library: libtheora.so.0: unused library 'usr/lib/x86_64-linux-gnu/libtheora.so.0.3.10'. (https://snapcraft.io/docs/linters-library)
- library: libzvbi-chains.so.0: unused library 'usr/lib/x86_64-linux-gnu/libzvbi-chains.so.0.0.0'. (https://snapcraft.io/docs/linters-library)
```
